name: BcStatistic
version: '1.0-SNAPSHOT'
main: com.bcstatistic.BcStatistic
authors: [X_32mx]
description: A placeholder extension plugin for BC
commands:
  bcstatistic:
    description: "[BcStatistic]Command"
    permission: BcStatistic.Main